---
- name: (Debian) Include os_family vars
  include_vars: Debian.yml
  when:
    - ansible_os_family == "Debian"
    - use_letsencrypt is defined
    - use_letsencrypt

- name: Check certbot_package
  fail:
    msg: |
      Invalid value for 'certbot_package': {{ certbot_package }}

      Supported types  : String
      Supported values : Any non-null string
  when: >-
    certbot_package is not string
    or certbot_package == 0

- name: Check certbot_packages
  fail:
    msg: |
      Invalid value for variable for 'certbot_packages': {{ certbot_packages }}

      Supported types  : List, String
      Supported values : Any non-null list or string
  when: >-
    certbot_package is not iterable
    or certbot_package == 0
