---
- name: Install Certbot.
  package:
    name: "{{ certbot_package }}"
    state: present

- name: Check if certificate already exists.
  stat:
    path: "/etc/letsencrypt/live/{{ site_domain }}/cert.pem"
  register: letsencrypt_cert
  when:
    - site_domain is defined
    - site_domain | length > 0

- name: Stop services to allow certbot to generate a cert.
  service:
    name: "{{ item }}"
    state: stopped
  when:
    - not letsencrypt_cert.stat.exists
    - certbot_stop_services is defined
    - certbot_stop_services | length > 0
  with_items: "{{ certbot_stop_services | unique }}"

- name: Generate new certificate if one doesn't exist.
  command: "{{ certbot_create_command }}"
  when:
    - not letsencrypt_cert.stat.exists
    - site_domain is defined
    - site_domain | length > 0
    - site_email is defined
    - site_email | length > 0

- name: Start services after cert has been generated.
  service:
    name: "{{ item }}"
    state: started
  when:
    - not letsencrypt_cert.stat.exists
    - certbot_stop_services is defined
    - certbot_stop_services | length > 0
  with_items: "{{ certbot_stop_services | unique }}"

- name: Generate DH Parameters
  openssl_dhparam:
    path: "{{ dh_path }}"
    size: "{{ cipher_size }}"
