---
# tasks file for ansible-role-letsencrypt

- name: (Let's Encrypt) Include variables and set facts
  include: facts.yml

- name: (Let's Encrypt) Install Let's Encrypt dependent packages
  package:
    name: "{{ certbot_packages }}"
    state: present
  when:
    - certbot_packages is defined
    - certbot_packages | length > 0
    - use_letsencrypt is defined
    - use_letsencrypt

# If site_domain doesn't point to the target host, Let's Encrypt is skipped
- name: (Let's Encrypt) Disable Let's Encrypt if DNS doesn't match
  set_fact:
    use_letsencrypt: false
  changed_when: dns_ip not in host_ips
  register: dns_check
  vars:
    dns_ip: "{{ lookup('dig', site_domain) }}"
    host_ips: "{{ ansible_all_ipv4_addresses }}"
  when:
    - use_letsencrypt is defined
    - use_letsencrypt
    - site_domain is defined
    - site_domain | length > 0
    - dns_ip not in host_ips

- name: (Let's Encrypt) Use Let's Encrypt if specified
  include: "letsencrypt.yml"
  when:
    - not dns_check.changed
    - use_letsencrypt is defined
    - use_letsencrypt
